language: python
python:
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
before_script:
  - psql -c 'create database toster;' -U postgres
services:
  - elasticsearch
script: python manage.py test
